### ISSUE TITLE
Feature: Object.extend

### ISSUE THREAD

**Issue by samme** [olivernn/supplement.js#4]
So I don't have to rely on jQuery.extend just to merge objects. ;)

**Comment by olivernn** [comment]
Adding something similar to $.extend would be good, it absolutely shouldn't be on Object.prototype though, instead it can be on the Object constructor, so `Object.extend`.

I'd be willing to accept a pull request with this addition, otherwise it may take me a little while to get around to it.  It would be a good addition.

**Comment by samme** [comment]
Meant to type "Object.extend". :)

I'll use [_.extend()](https://github.com/documentcloud/underscore/blob/master/underscore.js) in the meantime.
